sudo: false
language: python
branches:
  only:
  - master
cache: pip
env:
  global:
  - AWS_BUCKET=gottung.net
  - AWS_DEFAULT_REGION=us-east-2
  - AWS_ACCESS_KEY_ID=AKIAIFFUZ3LH37VBLV6A
  # AWS_SECRET_ACCESS_KEY
  - secure: "A7B5h+nfwoTeWTbyJef4UMSelF5oGi7lmR0SopzMahRuJmRCudS/E4LuHwzUPvvrMjNeBKN5rqAIsseXtsch6eovw31+jJlE0wM9fF6BQmV+HQGvK9Ppo5XRsgpfA/LxY2bzVrX3HUoZ3qTXy77OOr+o0wWhqKX6akC4UYoaPQk="
  # CLOUDFLARE_API_KEY
  - secure: "JJWXS3j8cBGh8MAy3+eH9o4j8YENfU9hHdUaB5AN2mAL/IyBglv1E5C8LbJivzw+OTZl3pMhtwyQ7FWKlKm6yAkznyvSCPQenVZq0roEYWficP6nHLzZZ1eHubIKW2gS3fSYDTcx5XfUKZJ0I90o7XlIEPQqaPIKuEwIXSbBkz4="
  # CLOUDFLARE_EMAIL
  - secure: "B7Wy55wpgLBlP1kAI7qQtSFEAs3C1LarWXCmmFkZnnvf35vi9XA3rnz3HMAZdMPF9XoDF5970pwBT10Gd0KTDQnGrG5ik/fbj+VNdb5jLHw1rWPhtaRF4XC2k+mN6zJsD7WoYj1EXAdt8Su3XsnV98BwtOnF0eFuRFPql8y/qMU="
  # CLOUDFLARE_ZONE_ID
  - secure: "MdMs82eU8+GYrAOhMYhHTh0vvQzI1J6fOFYsj9nYVmr/TP2yRbdtZBMHdsNHP3/Bzxa0R49Y4vqybPYsbdHp/nV459AJgCJ4UFTWmIW3E5RELsqwr93eQeghsz1yD7W4v64LciGttlXYE30203nM59qoCT+l/AoOVOlrPlW786E="
script: bin/s3-sync.sh && bin/purge-cloudflare-cache.sh
