sudo: false
language: python
branches:
  only:
  - master
cache: pip
env:
  global:
  - AWS_BUCKET=gottung.net
  - AWS_DEFAULT_REGION=us-east-2
  - AWS_ACCESS_KEY_ID=AKIAIFFUZ3LH37VBLV6A
  # AWS_SECRET_ACCESS_KEY
  - secure: "GhEE6B6j9jQ9bf0c7ixBlKh3mNQ1l70T3Fwb/VsdfIOSY2kmaB4iBDA9NlljzVb+EWBfXjf9zgxBZaLMmrsnOnPBGvm5oz5SRQE32dBavwGfKG2IxcUbgrL7XGjH2pGIe0BoO3CzY9Qb6Z1S6/mZ0INkmmjdd93UD64YmEr7Xuo="
  # CLOUDFLARE_API_KEY
  - secure: "cKft3OkcO+jjy9ckmu6kjJ45fiqiNlGPXay2jCsOCTQ7Jdq/8264VP4lkuHVUxhzHN7Mdy2gOhv4lce8R/cEjl8P8gr+oTTfbp7xW11BqBUXu5H8/Mh4B1tOZnAQnyylhWYicMQqLNsbGAHdllvH6D75VaemvQ+7YgYZkLN+Ed0="
  # CLOUDFLARE_EMAIL
  - secure: "YNmhyfaJyYykct2oPR2nxK7VkCXtttmml1KUfIHv2o6Yb3gtH3hdUUD+QjOSoRzZ11JBD+vcA0iEOHPF2MM/AyLwaVw7rCMUlOkB4pR6RtfdlFEvQefIhTYXK3ORMKt+Gugr2Yhw/yXu02pAvwRsUmeceUW3dCVn0n7yVsV7pC4="
  # CLOUDFLARE_ZONE_ID
  - secure: "MdMs82eU8+GYrAOhMYhHTh0vvQzI1J6fOFYsj9nYVmr/TP2yRbdtZBMHdsNHP3/Bzxa0R49Y4vqybPYsbdHp/nV459AJgCJ4UFTWmIW3E5RELsqwr93eQeghsz1yD7W4v64LciGttlXYE30203nM59qoCT+l/AoOVOlrPlW786E="
script: bin/s3-sync.sh && bin/purge-cloudflare-cache.sh
